### ISSUE TITLE
Will not let you out of the plugin

### ISSUE THREAD

**Issue by kc9ojn** [koolsb/fpp-nfl#9]
I was able to select the team and set it up. But the top menu was not pulling down. So the only option for getting out of the plugin was to go to the address bar and put in the IP and go back to the main index page. I use windows 11, and a K64. side note the plugin shows the game stats and such just fine so I am assuming it is working just fine. you just cant go to any other menu options to get out of the plugin. 

Thanks for what you do
Rod

**Comment by koolsb** [comment]
Should be fixed with the changes I just pushed.
